'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Script from "next/script";
import Footer from "../components/Footer";
import { Provider } from "react-redux";
import { store } from "../store/store";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/e19499ec5b.js" crossOrigin="anonymous"/>
        <link rel="stylesheet" href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css" />
        <link href='https://cdn.boxicons.com/fonts/animations.min.css' rel='stylesheet'></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
        <Provider store={store}>
        <Navbar/>
        {children}
        <Footer/>
        </Provider>
      </body>
    </html>
  );
}
