'use client'
import { Geist, Geist_Mono, Ubuntu, Ubuntu_Sans, Merienda } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Script from "next/script";
import Footer from "../components/Footer";
import { Provider } from "react-redux";
import { store } from "../store/store";
import { Providers } from './providers'





const geistMerienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"]
});

const geistUbuntu_Sans = Ubuntu_Sans({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"]
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/e19499ec5b.js" crossOrigin="anonymous"/>
        <link rel="stylesheet" href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css" />
        <link href='https://cdn.boxicons.com/fonts/animations.min.css' rel='stylesheet'></link>
      </head>
      <body className={`${geistMerienda.variable} ${geistUbuntu_Sans.variable} antialiased`}> 
        <Providers>
          <Provider store={store}>
            <Navbar/>
              {children}
            <Footer/>
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
